baseURL = 'https://roundup.stlgame.dev' # this will change eventually
languageCode = 'en-us'
title = 'St Louis Game Developer RoundUp'

enableEmoji = true

[params]
  explanation = "The St Louis Game Developer RoundUp is the official monthly digest of the St Louis Game Developer community. Curated by STLGameDev and built through community contributions, it aggregates news, project updates, resources, and upcoming events from our local game development scene."
  shareText = "Check out St Louis Game Dev RoundUp â„– %s!"
  keywords = "indie game development, game development, game developers, game dev, indie games, indie game developers, indie game dev, st louis, saint louis, missouri, mo"
  [params.social]
    instagram = "https://www.instagram.com/stlgamedev/"
    bluesky   = "https://bsky.app/profile/stlgame.dev"
    youtube   = "https://www.youtube.com/@stlgame-dev"
    twitter   = "https://x.com/stlgamedev"
    meetup    = "https://www.meetup.com/st-louis-game-developers/"
  [params.author]
    name = "Tim I Hely"
    email = "tim@axolstudio.com"


relativeURLs = false

publishDir = "public/"

disableKinds = ["taxonomy",  "term", "RSS", "taxonomyTerm","section"]
ignoreErrors = ["error-disable-taxonomy", "error-no-layout"]

[taxonomies]

[markup.goldmark.renderer]
  unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "(js|scripts|javascript)"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[services]
  [services.googleAnalytics]
    ID = "G-P29TNS4V9P"
  [services.scss]
    transpiler = "dartsass"

[outputFormats]
  [outputFormats.html]
    baseName = 'index'
    isHTML = true
    isPlainText = false
    mediaType = 'text/html'
    noUgly = true
    notAlternative = false
    permalinkable = true
    protocol = ''
    rel = 'canonical'
    weight = 10
  [outputFormats.email]
    baseName = 'email/index'
    isHTML = true
    isPlainText = false
    mediaType = 'text/html'
    noUgly = true
    notAlternative = true
    permalinkable = true
    weight = 0
    path = ""


[outputs]
  home = ["HTML", "RSS", "json"]
  section = ["HTML", "RSS"]
  page = ["HTML", "email"]

[module]
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.js"
    target = "assets/js/bootstrap.bundle.js"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/css/fonts"
  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font"
    target = "assets/scss/bootstrap-icons"
